services:
  jokopi-api:
    build:
      context: ./jokopi-api
      dockerfile: docker/Dockerfile
    container_name: jokopi-api
    ports:
      - "5000:5000"
    networks:
      - jokopi-net
    volumes:
      - ./certs:/app/certs:ro
    env_file:
      - ./jokopi-api/.env
    depends_on:
      - jokopi-postgres
      - jokopi-mongo
    restart: always
  
  jokopi-react:
    build:
      context: ./jokopi-react
      dockerfile: docker/Dockerfile.dev
    container_name: jokopi-react
    ports:
      - "3000:80"
    networks:
      - jokopi-net
    volumes:
      - ./jokopi-react/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/app/certs:ro
    environment:
      - PORT=80
      - REACT_APP_BACKEND_HOST=https://localhost:5000
      - REACT_APP_WEBSITE_NAME=Jokopi Coffee Shop
      - HTTPS=true
      - SSL_KEY_FILE=./certs/react.key
      - SSL_CRT_FILE=./certs/react.crt
    depends_on:
      - jokopi-api
    restart: always

  jokopi-postgres:
    image: postgres:17.5-bullseye
    container_name: jokopi-postgres
    # ports:
    #   - "5432:5432"
    networks:
      - jokopi-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./jokopi-api/db/ddl.sql:/docker-entrypoint-initdb.d/01_ddl.sql:ro
      - ./jokopi-api/db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql:ro
    environment:
      POSTGRES_USER: jokopi
      POSTGRES_PASSWORD: begbeg
      POSTGRES_DB: jokopi_db
    restart: always
  
  jokopi-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: jokopi-pgadmin
    ports:
      - "8082:80"
    networks:
      - jokopi-net
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jokopi.thelol.me
      PGADMIN_DEFAULT_PASSWORD: begbeg
    depends_on:
      - jokopi-postgres
    restart: always

  jokopi-mongo:
    image: mongo:4.4
    container_name: jokopi-mongo
    # ports:
    #   - "27017:27017"
    networks:
      - jokopi-net
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: begbeg
      MONGO_INITDB_DATABASE: jokopi_db
    restart: always

  jokopi-mongo-express:
    image: mongo-express:latest
    container_name: jokopi-mongo-express
    ports:
      - 8081:8081
    networks:
      - jokopi-net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: begbeg
      ME_CONFIG_MONGODB_URL: mongodb://root:begbeg@jokopi-mongo:27017/
    depends_on:
      - jokopi-mongo
    restart: always

volumes:
  postgres-data:
    name: postgres-data
  pgadmin-data:
    name: pgadmin-data
  mongo-data:
    name: mongo-data

networks:
  jokopi-net:
    name: jokopi-net
    driver: bridge
